/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ITodoItem,
} from './interfaces/app-interfaces';


export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface CompletedItems {}
  interface TodoAdd {}
  interface TodoItem {
    'todo': ITodoItem;
  }
  interface TodoList {
    'setTodos': (todos: ITodoItem[]) => Promise<void>;
  }
  interface ToolbarBadge {
    'setContent': (content: number) => Promise<void>;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCompletedItemsElement extends Components.CompletedItems, HTMLStencilElement {}
  var HTMLCompletedItemsElement: {
    prototype: HTMLCompletedItemsElement;
    new (): HTMLCompletedItemsElement;
  };

  interface HTMLTodoAddElement extends Components.TodoAdd, HTMLStencilElement {}
  var HTMLTodoAddElement: {
    prototype: HTMLTodoAddElement;
    new (): HTMLTodoAddElement;
  };

  interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {}
  var HTMLTodoItemElement: {
    prototype: HTMLTodoItemElement;
    new (): HTMLTodoItemElement;
  };

  interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {}
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };

  interface HTMLToolbarBadgeElement extends Components.ToolbarBadge, HTMLStencilElement {}
  var HTMLToolbarBadgeElement: {
    prototype: HTMLToolbarBadgeElement;
    new (): HTMLToolbarBadgeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'completed-items': HTMLCompletedItemsElement;
    'todo-add': HTMLTodoAddElement;
    'todo-item': HTMLTodoItemElement;
    'todo-list': HTMLTodoListElement;
    'toolbar-badge': HTMLToolbarBadgeElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {
    'onOnTodoItemCreated'?: (event: CustomEvent<any>) => void;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface CompletedItems extends JSXBase.HTMLAttributes<HTMLCompletedItemsElement> {}
  interface TodoAdd extends JSXBase.HTMLAttributes<HTMLTodoAddElement> {}
  interface TodoItem extends JSXBase.HTMLAttributes<HTMLTodoItemElement> {
    'onOnTodoItemCheck'?: (event: CustomEvent<any>) => void;
    'onOnTodoItemDelete'?: (event: CustomEvent<any>) => void;
    'onOnTodoItemUncheck'?: (event: CustomEvent<any>) => void;
    'todo'?: ITodoItem;
  }
  interface TodoList extends JSXBase.HTMLAttributes<HTMLTodoListElement> {
    'onOnTodoItemCheckedChanged'?: (event: CustomEvent<any>) => void;
    'onOnTodoItemDeleted'?: (event: CustomEvent<any>) => void;
  }
  interface ToolbarBadge extends JSXBase.HTMLAttributes<HTMLToolbarBadgeElement> {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'completed-items': CompletedItems;
    'todo-add': TodoAdd;
    'todo-item': TodoItem;
    'todo-list': TodoList;
    'toolbar-badge': ToolbarBadge;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


